version: "3.7"

services:

  php:
    build:
      context: "./.docker/php"
    image: "${PROJECT}_php"
    container_name: "${PROJECT}_php"
    ports:
      - 9000:9000
    volumes:
      - ./services/${PHP_SERVICE}:/srv/www/gdr
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
        - gdr-net

  web:
    build:
      context: "./.docker/web"
    image: "${PROJECT}_web"
    container_name: "${PROJECT}_web"
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./services/${PHP_SERVICE}:/srv/www/gdr
    depends_on:
      - php

  database:
    build:
      context: "./.docker/database"
    image: "${PROJECT}_database"
    container_name: "${PROJECT}_database"
    #restart: // always;unless-stopped
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./data/database:/var/lib/mysql
      - ./logs/database:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - php
    networks:
      - gdr-net

networks:
  gdr-net:
    driver: bridge