#==================== Setting up stage ====================#

# Create image based on the official nginx - Alpine image
FROM nginx:1.19-alpine

# Expose the listening port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]